// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8bmx47bh3OJLM7-tRqa5EJLmKiHDzfU',
    appId: '1:8302377041:web:cdf85b459f694355362070',
    messagingSenderId: '8302377041',
    projectId: 'prg1-83305',
    authDomain: 'prg1-83305.firebaseapp.com',
    storageBucket: 'prg1-83305.firebasestorage.app',
    measurementId: 'G-Z3SEKFKZNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYx39-AOanx9_Z7leFX_7Wqf9xdJXFnxU',
    appId: '1:8302377041:android:0b8deb08e86df627362070',
    messagingSenderId: '8302377041',
    projectId: 'prg1-83305',
    storageBucket: 'prg1-83305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldFSaN4rMtFhc0zxxbwLQ9ZuWEBOQxTs',
    appId: '1:8302377041:ios:a1a5e4963bc52c25362070',
    messagingSenderId: '8302377041',
    projectId: 'prg1-83305',
    storageBucket: 'prg1-83305.firebasestorage.app',
    iosBundleId: 'com.example.prg1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAldFSaN4rMtFhc0zxxbwLQ9ZuWEBOQxTs',
    appId: '1:8302377041:ios:a1a5e4963bc52c25362070',
    messagingSenderId: '8302377041',
    projectId: 'prg1-83305',
    storageBucket: 'prg1-83305.firebasestorage.app',
    iosBundleId: 'com.example.prg1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz8bmx47bh3OJLM7-tRqa5EJLmKiHDzfU',
    appId: '1:8302377041:web:03894e08ebdceebf362070',
    messagingSenderId: '8302377041',
    projectId: 'prg1-83305',
    authDomain: 'prg1-83305.firebaseapp.com',
    storageBucket: 'prg1-83305.firebasestorage.app',
    measurementId: 'G-DKRWYKR60Y',
  );
}
